### ISSUE TITLE
ERROR: ResolutionImpossible: Cannot install on Python3.10

### ISSUE THREAD

**Issue by petarpetarpetar** [clarinsi/classla-stanfordnlp#31] opened 2022-02-13 13:42 UTC
Hello guys,

The library seems really good and I want to try it out. However, upon running `pip install classla` I'm getting the following error:
```

ERROR: Cannot install classla==0.0.1, classla==0.0.10, classla==0.0.11, classla==0.0.2, classla==0.0.3, classla==0.0.4, classla==0.0.6, classla==0.0.7, classla==0.0.8, classla==0.0.9, classla==1.0.0, classla==1.0.1, classla==1.0.2 and classla==1.1.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    classla 1.1.0 depends on torch>=1.3.0
    classla 1.0.2 depends on torch>=1.3.0
    classla 1.0.1 depends on torch>=1.3.0
    classla 1.0.0 depends on torch>=1.3.0
    classla 0.0.11 depends on torch<=1.5.0 and >1.3.0
    classla 0.0.10 depends on torch<=1.5.0 and >1.3.0
    classla 0.0.9 depends on torch<=1.5 and >1.3.0
    classla 0.0.8 depends on torch>1.3.0
    classla 0.0.7 depends on torch>1.3.0
    classla 0.0.6 depends on torch>1.3.0
    classla 0.0.4 depends on torch>1.3.0
    classla 0.0.3 depends on torch>1.3.0
    classla 0.0.2 depends on torch>1.3.0
    classla 0.0.1 depends on torch>1.3.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```
I couldn't find a solution myself and that's why I'm turning to you for help <3

**Comment by nljubesi** [comment] 2022-02-14 07:50
@petarpetarpetar thank you for reporting. @lkrsnik, can you, please investigate?

@petarpetarpetar In the meantime, can you check that this is not due to a faulty pip? From your output it seems that pip is trying to install all versions, which is not expected behaviour. The behaviour might be related to https://github.com/pypa/pip/issues/9284. Can you run `pip install -U pip` to get the newest pip and then try installing classla again?

**Comment by lkrsnik** [comment] 2022-02-14 08:15
Classla doesn't work with python3.10, because underlying libraries (namely torch - https://github.com/pytorch/pytorch/issues/67669) are not updated yet.

I suggest downgrading python to an older version.

**Comment by nljubesi** [comment] 2022-02-14 08:48
Thank you, @lkrsnik! More knowledgeable as usual. @petarpetarpetar you know what to do. Closing this issue.

**Closed as completed by nljubesi** 2022-02-14 08:48 UTC
Labels: question

**Comment by petarpetarpetar** [comment] 2022-02-14 08:56
Thanks guys
